### PR TITLE
#597 fix issue 

### PR DESCRIPTION
**Pull request by mlatzko**
Fix issue causing type error while bundled with other js code.

### CODE REVIEW

**Comment by ValentinH** [comment]
Do you need this if you use the `dist` files?

**Comment by mlatzko** [comment]
Yes I would need this in the `dist` files.

But the the `src` files need them as well, cause the missing semicolon should raise a jshint warning as this little example demonstrates.

Just copy/paste to http://jshint.com/.
```
(function(root, factory){
  "use strict";
  

})(this, function(angular){
	"use strict";
  
})
```
Result: 1 Warning - Line 8 - Missing semicolon.

**Comment by mlatzko** [comment]
Any progress, we can either close the pull-request if there is a way to add the needed semicolon in the `dist` files or we can apply the semicolon in `src` files both solution are fine with me. 

Let me know if I can help out.

**Comment by ValentinH** [comment]
The thing is that you can see this issue the other way around: we already add a `;` at the beginning of the code (https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L11), thus the issue can also be seen as coming from the library that is appended after this one in your concatenated file.

We are using a really standard tool, aka Prettier, without any semicolons in the source files (except from the first mandatory one). The issue might be coming from your packaging system as well.

**Comment by ValentinH** [comment]
Moreover, using https://github.com/angular-slider/angularjs-slider/blob/master/dist/rzslider.min.js should be fine since the last char is the semicolon.

**Comment by mlatzko** [comment]
> Moreover, using https://github.com/angular-slider/angularjs-slider/blob/master/dist/rzslider.min.js should be fine since the last char is the semicolon.

Thx for pointing this out and sorry for the inconvenience I now use the minified version in my build process.

**Comment by ValentinH** [comment]
No problem ;)

**Pull request closed without merging**
