### PR TITLE
feat(directive): Add function to customize color of ticks

### PR DESCRIPTION
**Pull request by amit777**
Pass a custom function to the slider options to allow for dynamic tick color determination

none

### CODE REVIEW

**Comment by ValentinH** [comment]
This one is correct, but please remove the change about outline...

**Comment by amit777** [comment]
I can remove change on outline and keep it in my fork.  Just curious if there a specific reason you don't want it merged?

**Comment by ValentinH** [comment]
Outline can be disabled by setting keyboardSupport to false. The outline is here to know which handle is selected and can be moved with keyboard.

Also your pull request is missing a test case for the new feature. You can copy the getPointerColor tests to cover your changes. ;)

**Comment by amit777** [comment]
got it.. i'll add the tests and remove the outline change

**Pull request closed without merging**
