### PR TITLE
Update to templateUrl to allow compilable string values

### PR DESCRIPTION
**Pull request by haxxxton**
As per [issue 409](https://github.com/angular-slider/angularjs-slider/issues/409) there is a request for custom values to be allowed as part of the templateUrl parameter.

ie.

``` html
<rzslider
      rz-slider-model="slider_custom_template.minValue"
      rz-slider-high="slider_custom_template.maxValue"
      rz-slider-options="slider_custom_template.options"
      rz-slider-tpl-url="{{ vm.userSelectedOption }}/rzSliderTemplate.html"
    ></rzslider>
```

Unfortunately, the `templateUrl` directive option occurs before the scope compiles the double brackets, as such loading of the template has been moved within the link option. Because of the nature of this method, it has meant that the slider contents are now one level deeper (as the template html is loaded inside the directive element). This has meant the addition of a container class and style for the slider element

I have not added additional tests or documentation for this upgrade, however all current tests are passing.

### CODE REVIEW

**Comment by ValentinH** [comment]
To be honest, I really don't like this solution. It feels more like a workaround than something that should be integrated in the library (having the load yourself the template , compile and attach the content to the DOM).

Thus, I would prefer to keep this solution in a fork.

**Comment by haxxxton** [comment]
No problem, if there is other solutions for compiling custom templates on the fly i am open to exploring them, as ive had to use this method before in a couple of other projects.

Would a solution that uses `ng-include` feel nicer to you? ([Example](http://stackoverflow.com/a/21835866/648350))

**Comment by ValentinH** [comment]
I have try that but it doesn't work since the slider needs the template content to initialize properly. Did you manage to make it work?

**Comment by haxxxton** [comment]
I think as long as you wait until after the next digest cycle, ie. after a 0 length `$timeout`. The template should be included into the directive and you could initialise the slider. I will have a look over the weekend :)

**Pull request closed without merging**
