### PR TITLE
fix(options): Fix showing limit labels when pointer labels are always hidden

### PR DESCRIPTION
**Pull request by trodi**
Previously limit labels would be hidden based on the position of the pointer labels even if user
options hide pointer labels.

This addresses #353

### CODE REVIEW

**Comment by ValentinH** [comment]
Thanks for this PR, it looks good. 

I'm wondering if, when the hidePointerLabels is toggled at runtime, everything will work as expected. Indeed, if the option is off and the floor/ceil label is hidden because the pointer is next to it, and the option is turned on, the floor/ceil label will stay hidden while they should be visible...

**Comment by ValentinH** [comment]
I'm away from computer until the end of the weekend so I'll try this scenario later. ;)

**Comment by trodi** [comment]
Here's a [JSFiddle](http://jsfiddle.net/dqgn9oLe/) which should demonstrate your use case. I believe it handles as expected. Below are concrete steps to test (as I understood them).

1. `hidePointerLabels: false`
2. move point to force min limit to hide
3. programmatically toggle  `hidePointerLabels: true`
4. min label is visible and pointer label is hidden

**Comment by ValentinH** [comment]
Indeed, this corresponds to what I was talking about. Good job! ;)

**Pull request merged**
