### PR TITLE
Add a draggableRangeOnly options. 

### PR DESCRIPTION
**Pull request by ValentinH**
As asked in #196 and #199.
Demo: http://jsfiddle.net/opnrb0hL/

@FantasyLions @yelnar is it what you wanted?

### CODE REVIEW

**Comment by ValentinH** [comment]
OK I'll merge #203 before then . I'll do it later today.

**Comment by FantasyLions** [comment]
yes! is awesome.Maby can add this feature:move the whole slider when you drag the handle

**Comment by yelnar** [comment]
Cool! And also I think it is would be better if two edges of slider was draggable too. Thank you.

**Comment by ValentinH** [comment]
Indeed you are both right. I just added what you wanted and also keyboard support.

**Comment by yelnar** [comment]
@ValentinH great, thanks!

**Pull request merged**
