### PR TITLE
add grunt task that copies the final css to scss file

### PR DESCRIPTION
**Pull request by ronnyrin**
I know that you don't want to maintain two codebases. With this solution, you won't have to.
We need a way to import the final css in our scss file and currently importing css is not supported.

### CODE REVIEW

**Comment by ronnyrin** [comment]
Thanks, Can you bump the version?

**Comment by ValentinH** [comment]
Done -> 5.8.3

**Comment by ronnyrin** [comment]
Maybe we can just rename the scss file so there will be no conflict. Importing raw CSS didn't work for me.

**Comment by ValentinH** [comment]
Are you using a recent version of SASS like explain in the linked issue?

**Comment by ronnyrin** [comment]
Yes. It doesn't work.. I'm using [grunt-contrib-compass](https://github.com/gruntjs/grunt-contrib-compass)
```
 error app/styles/main.scss (Line 18 of app/styles/components/...: File to import not found or unreadable: angularjs-slider/dist/rzslider.
Load paths:
  /Users/..../app/bower_components
```

```
✗ ./node_modules/node-sass/bin/node-sass -v
node-sass       3.10.1  (Wrapper)       [JavaScript]
libsass         3.3.6   (Sass Compiler) [C/C++]```

**Comment by ValentinH** [comment]
It seems that you are missing the .css part of your file pat, don't you?

**Comment by ronnyrin** [comment]
No, if you add the .css suffix then it just [transform](https://github.com/sass/libsass/pull/754#issuecomment-96062994) it to `@import url(file.css);` and that won't work at all because the browser won't look in the bower folder.

**Pull request merged**
