### PR TITLE
Adding a new option showSelectionBarSingle to allow getting the rz-se…

### PR DESCRIPTION
**Pull request by asafblum**
…lected on a single tick

### CODE REVIEW

**Comment by asafblum** [comment]
image

**Comment by ValentinH** [comment]
Thanks for this PR. However, I think that the option name is not understandable. What does it really do? Could you provide a demo using JSFiddle?

Also this is breaking the test coverage, so a new unit test is needed.

**Comment by asafblum** [comment]
Hi @ValentinH please take a look: http://jsfiddle.net/asafblum/wtboevs4/1/
also added a test does this option make sense or I can achieve this with out the new option:
I'd like to get the selected class on the exact tick for the current value and not from

**Comment by ValentinH** [comment]
Thanks for the example. I'm starting to wonder if an option is needed and if it should just be the default behavior to add this class to the tick. ;)

**Comment by asafblum** [comment]
Hey @ValentinH ,
What's the direction on this one? can I close the PR?

will you use it?

**Comment by ValentinH** [comment]
I think we should not add a new option, but fix the current behavior by always setting `.rz-selected` on a single slider current value tick.

**Pull request closed without merging**
