### PR TITLE
First attempt to add colouring of outside areas for range sliders

### PR DESCRIPTION
**Pull request by GMaxera**
Trying to implement #523 

I added a new option: "showOuterSelectionBars" (default: false) that when true will show two coloured area outside the selection in case of range sliders.

I also added two new .css classes for customise the colour of these two new areas.

Please review my code and let me know if meet your quality expectation ... and of course tell me if you spot any bugs on it :-)

Demo: http://jsfiddle.net/z3dLacot/

### CODE REVIEW

**Comment by ValentinH** [comment]
Thanks for this! 👍 I have added a demo to your pull request description, but you need to generate the dist files for it to work (run `grunt`) and add the new dist files.

**Comment by GMaxera** [comment]
:-D I need to figure out how to use grunt :-) ... I've never used it

**Comment by ValentinH** [comment]
You just need to run `npm install` to install all the dependencies and then `npm run grunt`.

**Comment by GMaxera** [comment]
I had to install grunt-cli and grunt-init globally and run the global "grunt" script.
"npm run grunt" was failing :-(

**Comment by ValentinH** [comment]
A few first remarks:
- you need to handle `rightToLeft: true` (left outer and right outer should be inverted)
- existing tests should be fixed
- new tests should be added to handle this new feature

**Comment by GMaxera** [comment]
I need some guidance to understand what to do for code coverage.
It's the first time for me :-)

**Comment by GMaxera** [comment]
Ok, I think I've managed :-)
maybe with too much commits :-( sorry.

Let me know if you want other things

**Comment by ValentinH** [comment]
Great contribution! 👍  No worries for the commits, I'll squash and merge.

**Comment by ValentinH** [comment]
One last thing to be perfect: document the new option in the README and update the bower/npm versions to 6.4.0. Don't forget to run `grunt` to generate the dist files after the version update. 🙂

**Comment by GMaxera** [comment]
Ok, thanks. I'll do tonight (22:00 UK time)

**Pull request merged**
