### PR TITLE
feat(ticks): Accept numbers for showTicks/showTicksValues

### PR DESCRIPTION
**Pull request by ValentinH**
Thanks to this feature, you can display ticks at intermediate positions without setting a fixed step.
As requested in #259.
Demo: http://jsfiddle.net/xaa0qox1/

A few problems found so far:
- [x] clicking on a tick should set the slider value exactly to the tick value 
- [x] clicking on a tick value should set the slider value exactly to the tick value
- [x] when using `showTicksValues`, the pointer label is hidden and so we don't really know the current value. This is because when the `showTicks*` options were only boolean, the labels were useless since they were replaced by the ticks values.
- [x] complete unit tests

### CODE REVIEW

**Comment by lookfirst** [comment]
Nice work!

The UX that I've seen used elsewhere is a bit different. The tick value is below and the slider tick value is shown above as it is dragged. It hides when the mouse is not over it.

http://take.ms/aenJI  - with the mouse over the slider (shows the value above)
http://take.ms/zbbhu - hidden when the mouse is not over the slider

I can also click on the values below the line to set the slider value.

**Comment by ValentinH** [comment]
In my opinion, hiding the value when the mouse is not on the slider is not an option since it is important for the slider to be fully understandable without any additional widgets.

Thanks to CSS, ticks can already been set on the bottom but the slider need to work properly for ticks with top and bottom.

**Comment by lookfirst** [comment]
Sure, I agree with you - I don't like hidden UX.

**Comment by ValentinH** [comment]
@lookfirst  I have updated the demo and add handling for showTicksValues. Can I get your feedback please?

**Comment by lookfirst** [comment]
:+1:

**Comment by ValentinH** [comment]
Ok then I just need to complete to unit tests.

**Comment by johnsheldon** [comment]
Any ETA for the release which contains this feature? We just so happened to need it and saw it was being implemented.

**Comment by ValentinH** [comment]
Normally, the feature is ready, only the unit tests are missing. I just need to find the time to write them...

Does the demo looks good to you?

**Comment by lookfirst** [comment]
Just integrated this into my app... thanks! screenshot: http://take.ms/RIYCH

**Comment by ValentinH** [comment]
Great! :)

**Pull request merged**
