### PR TITLE
feat($compile): adds labelOverlapSeparator as an option

### PR DESCRIPTION
**Pull request by ben-henoida**
The labelOverlapSeparator option allows the user to specify what string to use to separate the
labels when they overlap. The previous hardcoded string ' - ' could indeed be mistaken as a minus
sign. To avoid introducing a breaking change, the default is the previous value: ' - '. Tests and
README.md modified accordingly.

Demo: http://jsfiddle.net/sLxkwv9s/
(Compare to original problem: http://jsfiddle.net/04sr3ty0/1/)

### CODE REVIEW

**Comment by ben-henoida** [comment]
I have removed the file, would it be a good idea to add it to .gitignore ?

**Comment by ValentinH** [comment]
Indeed, can you add this as well? :)

**Comment by ValentinH** [comment]
Perfect!

**Comment by ValentinH** [comment]
Released! https://github.com/angular-slider/angularjs-slider/releases/tag/6.5.0

**Pull request merged**
