### PR TITLE
added classes to floor and ceil label to allow styling

### PR DESCRIPTION
**Pull request by jezmck**

### CODE REVIEW

**Comment by jezmck** [comment]
Excellent, thank you.

Do you know when this will get out to NPM?

**Comment by ValentinH** [comment]
I was waiting to finish the #335 PR before doing a single major release... but I think I will do a 3.0 release soon and do a 4.0 later then.

**Comment by ValentinH** [comment]
3.0 version released on NPM ;) Just check the CHANGELOG.md before updating to understand the breaking change (don't worry, nothing big).

**Comment by jezmck** [comment]
Oh fantastic, thank you.

**Pull request merged**
