### PR TITLE
feat(logScale): Implement a logScale option

### PR DESCRIPTION
**Pull request by ValentinH**
Implement a logScale option to display sliders with logarithmic scale.
Demo: http://jsfiddle.net/v6spvvpg/

Todo:
- [x] handle ticks

### CODE REVIEW

**Comment by BrunoCartier** [comment]
This would be a useful feature :+1:

**Comment by ValentinH** [comment]
I could merge it but it won't support ticks cause I couldn't find a way to display them correctly.

**Comment by seb2578** [comment]
Hi Valentin,
Greetings from a French expatriate from NYC.
Would you consider merging this pull request (even without ticks) ? I would definitely use it if it was made available.
Sébastien

**Comment by ValentinH** [comment]
OK I'll merge it. Just need to add tests then. ;)

**Comment by ValentinH** [comment]
This was merged and released under 5.7.0

**Pull request merged**
