### PR TITLE
fixed reset of maxH element

### PR DESCRIPTION
**Pull request by nibblesnbits**
Calling `this.maxH.css('display', null);` does not reset the style.  Passing `''` does.  This fixes an issue where the max slider bubble does not reappear when updating the model.

### CODE REVIEW

**Comment by ValentinH** [comment]
Demo or it didn't happen! :D

**Comment by ValentinH** [comment]
I got it for you: https://jsfiddle.net/7tfbnj92/ (last example)

The problem is when JQuery is used....

**Comment by ValentinH** [comment]
Also, could you generate the dist files by runnning `grunt`please?

**Comment by nibblesnbits** [comment]
updated

**Comment by ValentinH** [comment]
Just to make it perfect: could you rebase on master so there is no conflict, merge everything  so there is only one commit, and remove the temp folder / modified git .ignore .

**Comment by ValentinH** [comment]
I can't merge it as is because there are conflicts.

You need to rebase your branch on master and do the other steps I mentioned above.
Otherwise, I can do it directly but you won't appear as a contributor..

**Comment by ValentinH** [comment]
Merged manually.

**Pull request closed without merging**
