### PR TITLE
fix: Fix for wrong slider drag when having many touches simultaneous

### PR DESCRIPTION
**Pull request by daniela-mateescu**
#534 
Sample at: http://jsfiddle.net/fq6xkod4/ . This sample requires a device with a touch screen. It illustrates that the possibility to use both sliders simultaneously.

### CODE REVIEW

**Comment by ValentinH** [comment]
Thanks for this PR. It is really clean and provide full test coverage! Thanks 👍

**Comment by daniela-mateescu** [comment]
Hello! Thank you very much for integrating the PR, but we have a little problem with this. I saw that you did a refactor before integration. It is all ok with this refactor, except one little problem. At onStart() method, instead of memorizing the  ehEnd handler to be removed later like this: ` this.ehEndToBeRemovedOnEnd = ehEnd;`, you have sent this as a parameters like this: ` ehEnd = angular.bind(this, this.onEnd, ehMove, ehEnd);`. The problem with this code is that the `ehEnd` variable will be always undefined when passing it to the `angular.bind` method call.

Thank you in advance.

**Comment by ValentinH** [comment]
I modified after merging yesterday because of this issue #536 that was related to this PR. But you are right, I did it a bit too quickly and it's wrong... 

It proves that even with 100% test coverage, some tests are still missing because this should have been caught. I'm fixing it right away by keeping the way you were doing it but also by providing the correct event name.

**Comment by ValentinH** [comment]
Master should be fixed on http://jsfiddle.net/mejsy5d2/

**Comment by daniela-mateescu** [comment]
Hello,
Thank you very much for the fix. It works great now.

**Pull request merged**
