### PR TITLE
Add BoundPointerLabels Option

### PR DESCRIPTION
**Pull request by andreytkachenko**
Added new boolean option - boundPointerLabels (default: true).
On True: nothing changed.
On False: pointer label will not stick to the ends of slider.

### CODE REVIEW

**Comment by ValentinH** [comment]
Could you add a demo please by forking the default jsfiddle?  :)

**Comment by andreytkachenko** [comment]
Hi, here is the demo https://jsfiddle.net/andreytkachenko64/2v6173zs/5/

The idea is to allow pointer labels move like it was in 1.x versions

**Comment by ValentinH** [comment]
It only works for the value label but don't you think it should have the same behaviour for floor and ceiling labels?

Also unit tests covering your changes are missing.

**Comment by andreytkachenko** [comment]
Only pointer labels are movable, so it is impossible case for floor and ceiling labels because they are fixed in one place (and it is easy to locate them through css). But I didn't find any good way to move this logic to css (instead js parameters).

**Comment by ValentinH** [comment]
Thanks ! (and sorry for the delay of the merge)

**Pull request merged**
